// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer Menu → Menu Item*
 */
export interface FooterMenuDocumentDataMenuItemItem {
  /**
   * Title field in *Footer Menu → Menu Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.menu_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Footer Menu → Menu Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.menu_item[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer Menu documents
 */
interface FooterMenuDocumentData {
  /**
   * Menu Item field in *Footer Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.menu_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_item: prismic.GroupField<Simplify<FooterMenuDocumentDataMenuItemItem>>;

  /**
   * Facebook Link field in *Footer Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram Link field in *Footer Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.instagram_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Copyright field in *Footer Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Footer Menu document from Prismic
 *
 * - **API ID**: `footer_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterMenuDocumentData>,
    "footer_menu",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | TextWithBackgroundSlice
  | PageHeaderSlice
  | HeroSlice
  | CallToActionWithImageSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TextWithBackgroundSlice
  | PageHeaderSlice
  | HeroSlice
  | CallToActionWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Site Navigation → Menu Item*
 */
export interface SiteNavigationDocumentDataMenuItemItem {
  /**
   * Title field in *Site Navigation → Menu Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.menu_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Site Navigation → Menu Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.menu_item[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Site Navigation → CTA Item*
 */
export interface SiteNavigationDocumentDataCtaItemItem {
  /**
   * Title field in *Site Navigation → CTA Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.cta_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL field in *Site Navigation → CTA Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.cta_item[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Site Navigation documents
 */
interface SiteNavigationDocumentData {
  /**
   * Menu Item field in *Site Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.menu_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_item: prismic.GroupField<
    Simplify<SiteNavigationDocumentDataMenuItemItem>
  >;

  /**
   * CTA Item field in *Site Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.cta_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta_item: prismic.GroupField<Simplify<SiteNavigationDocumentDataCtaItemItem>>;

  /**
   * Logo field in *Site Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site_navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Site Navigation document from Prismic
 *
 * - **API ID**: `site_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteNavigationDocumentData>,
    "site_navigation",
    Lang
  >;

export type AllDocumentTypes =
  | FooterMenuDocument
  | HomePageDocument
  | PageDocument
  | SiteNavigationDocument;

/**
 * Primary content in *CallToActionWithImage → Default → Primary*
 */
export interface CallToActionWithImageSliceDefaultPrimary {
  /**
   * Title field in *CallToActionWithImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *CallToActionWithImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Image field in *CallToActionWithImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Gray Background field in *CallToActionWithImage → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: call_to_action_with_image.default.primary.gray_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  gray_background: prismic.BooleanField;
}

/**
 * Primary content in *CallToActionWithImage → Items*
 */
export interface CallToActionWithImageSliceDefaultItem {
  /**
   * CTA Title field in *CallToActionWithImage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.items[].cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA URL field in *CallToActionWithImage → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.items[].cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CallToActionWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionWithImageSliceDefaultPrimary>,
  Simplify<CallToActionWithImageSliceDefaultItem>
>;

/**
 * Primary content in *CallToActionWithImage → Flipped → Primary*
 */
export interface CallToActionWithImageSliceFlippedPrimary {
  /**
   * Title field in *CallToActionWithImage → Flipped → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.flipped.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *CallToActionWithImage → Flipped → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.flipped.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Image field in *CallToActionWithImage → Flipped → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.flipped.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Gray Background field in *CallToActionWithImage → Flipped → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: call_to_action_with_image.flipped.primary.gray_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  gray_background: prismic.BooleanField;
}

/**
 * Primary content in *CallToActionWithImage → Items*
 */
export interface CallToActionWithImageSliceFlippedItem {
  /**
   * CTA Title field in *CallToActionWithImage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.items[].cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA URL field in *CallToActionWithImage → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_image.items[].cta_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Flipped variation for CallToActionWithImage Slice
 *
 * - **API ID**: `flipped`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithImageSliceFlipped = prismic.SharedSliceVariation<
  "flipped",
  Simplify<CallToActionWithImageSliceFlippedPrimary>,
  Simplify<CallToActionWithImageSliceFlippedItem>
>;

/**
 * Slice variation for *CallToActionWithImage*
 */
type CallToActionWithImageSliceVariation =
  | CallToActionWithImageSliceDefault
  | CallToActionWithImageSliceFlipped;

/**
 * CallToActionWithImage Shared Slice
 *
 * - **API ID**: `call_to_action_with_image`
 * - **Description**: CallToActionWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithImageSlice = prismic.SharedSlice<
  "call_to_action_with_image",
  CallToActionWithImageSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Header field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Subheader field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheader
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheader: prismic.KeyTextField;

  /**
   * Primary CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Parallax → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * Title field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Background Image field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Primary CTA field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    | "Primary"
    | "Secondary"
    | "Primary Outline"
    | "Primary White Outline"
    | "Link"
    | "Link White"
  >;

  /**
   * Secondary CTA field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    | "Primary"
    | "Secondary"
    | "Primary Outline"
    | "Primary White Outline"
    | "Link"
    | "Link White"
  >;

  /**
   * Overlay Color field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.overlay_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  overlay_color: prismic.ColorField;

  /**
   * Overlay Opacity field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.overlay_opacity
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  overlay_opacity: prismic.SelectField<
    "100" | "90" | "80" | "70" | "60" | "50" | "40" | "30" | "20" | "10"
  >;
}

/**
 * Default variation for Parallax Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Parallax*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * Parallax Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Primary content in *TextWithBackground → Default → Primary*
 */
export interface TextWithBackgroundSliceDefaultPrimary {
  /**
   * Header field in *TextWithBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Subheader field in *TextWithBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.default.primary.subheader
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheader: prismic.KeyTextField;

  /**
   * Background Color field in *TextWithBackground → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Text Theme field in *TextWithBackground → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.default.primary.text_theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_theme: prismic.SelectField<"Dark" | "Light">;

  /**
   * Body field in *TextWithBackground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Primary CTA field in *TextWithBackground → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    | "Primary"
    | "Secondary"
    | "Primary Outline"
    | "Primary White Outline"
    | "Link"
    | "Link White"
  >;
}

/**
 * Default variation for TextWithBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextWithBackground*
 */
type TextWithBackgroundSliceVariation = TextWithBackgroundSliceDefault;

/**
 * TextWithBackground Shared Slice
 *
 * - **API ID**: `text_with_background`
 * - **Description**: TextWithBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithBackgroundSlice = prismic.SharedSlice<
  "text_with_background",
  TextWithBackgroundSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterMenuDocument,
      FooterMenuDocumentData,
      FooterMenuDocumentDataMenuItemItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SiteNavigationDocument,
      SiteNavigationDocumentData,
      SiteNavigationDocumentDataMenuItemItem,
      SiteNavigationDocumentDataCtaItemItem,
      AllDocumentTypes,
      CallToActionWithImageSlice,
      CallToActionWithImageSliceDefaultPrimary,
      CallToActionWithImageSliceDefaultItem,
      CallToActionWithImageSliceFlippedPrimary,
      CallToActionWithImageSliceFlippedItem,
      CallToActionWithImageSliceVariation,
      CallToActionWithImageSliceDefault,
      CallToActionWithImageSliceFlipped,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      TextWithBackgroundSlice,
      TextWithBackgroundSliceDefaultPrimary,
      TextWithBackgroundSliceVariation,
      TextWithBackgroundSliceDefault,
    };
  }
}
