// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action_with_image: dynamic(() => import("./CallToActionWithImage")),
  hero: dynamic(() => import("./Hero")),
  icons: dynamic(() => import("./Icons")),
  page_header: dynamic(() => import("./Parallax")),
  text_with_background: dynamic(() => import("./TextWithBackground")),
};
